
console.log("Distintos tipos de datos que existen en JS");
console.log('1.- ' + typeof 42);
console.log('2.- ' + typeof 'Veinticinco');
console.log('3.- ' + typeof -666);
console.log('4.- ' + typeof true);
console.log('5.- ' + typeof 0);
console.log('6.- ' + typeof '');
console.log('7.- ' + typeof null);
console.log('8.- ' + typeof undefined);
console.log('9.- ' + typeof FALSE);

console.log('Otros ejemplos: ');
console.log('1.- ' + typeof 3.14);
console.log('2.- ' + typeof 3.14e-10);
console.log('3.- ' + typeof '3.14e+10');
console.log('4.- ' + typeof false);
console.log('5.- ' + typeof 'false');
console.log('6.- ' + typeof 'null');
console.log('7.- ' + typeof 'undefined');
console.log('8.- ' + typeof NaN);
console.log('9.- ' + typeof Infinity);
console.log('10.- ' + typeof -Infinity);
console.log('11.- ' + typeof 0xFF);
console.log('12.- ' + typeof 0b101010);
console.log('13.- ' + typeof 0o777);
console.log('14.- ' + typeof Symbol('foo'));
console.log('15.- ' + typeof BigInt(1234567890123456789012345678901234567890));
console.log('16.- ' + typeof new Date());
console.log('17.- ' + typeof function(){});
console.log('18.- ' + typeof [1, 2, 3]);
console.log('19.- ' + typeof {a: 1, b: 2});
console.log('20.- ' + typeof new Map());
console.log('21.- ' + typeof new Set());
console.log('22.- ' + typeof new WeakMap());
console.log('23.- ' + typeof new WeakSet());
console.log('24.- ' + typeof new ArrayBuffer(8));
console.log('25.- ' + typeof new Int8Array(8));
console.log('26.- ' + typeof new Uint8Array(8));
console.log('27.- ' + typeof new Float32Array(8));
console.log('28.- ' + typeof new Float64Array(8));
console.log('29.- ' + typeof new Array(8));
console.log('30.- ' + typeof new Object());
console.log('31.- ' + typeof new String('Hola'));
console.log('32.- ' + typeof new Number(42));
console.log('33.- ' + typeof new Boolean(true));
console.log('34.- ' + typeof new RegExp('a-z'));
console.log('35.- ' + typeof new Error('Error de prueba'));
console.log('36.- ' + typeof new Promise(function(resolve, reject) {}));